[project]
name = "irail-ingestion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sanneau", email = "anneausimon@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.6",
    "pyarrow>=25.0.1",
    "requests>=2.34.2",
    "tenacity>=9.1.4",
]

[project.scripts]
irail-ingestion = "irail_ingestion:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "G", "N"]
